#!/bin/bash
set -e

image="pandoc-latex:latest"

prefix=()
opts=()
opts+=(--rm)
#opts+=(--entrypoint sh)
opts+=(--tty)
opts+=(--interactive)
MOUNT_HOME="n"
MOUNT_PWD="y"

if [[ "$(uname -o 2> /dev/null)" == "Msys" ]] ; then
	declare -x MSYS_NO_PATHCONV=1
	prefix+=(winpty)
	[[ "$MOUNT_PWD" == "y" ]] && opts+=(--volume "/$(pwd -W)":/data)
	WHOME="$(cd "$HOME" && pwd -W)"
	[[ "$MOUNT_HOME" == "y" ]] && opts+=(--volume "/$WHOME":/home/$USER)
else
	opts+=(--user "$(id -u)":"$(id -g)")
	[[ "$MOUNT_PWD" == "y" ]] && opts+=(--volume "${PWD}":/data)
	[[ "$MOUNT_HOME" == "y" ]] && opts+=(--volume "$HOME":/home/$USER)
fi

"${prefix[@]}" docker run "${opts[@]}" ${image} "${@}"
