#!/bin/bash
set -e

image="pandoc-mermaid:latest"
prefix=()
opts=()
opts+=(--tty)
opts+=(--interactive)
opts+=(--rm)
opts+=(--user "$(id -u)":"$(id -g)")

if [[ "$(uname -o)" == "Msys" ]] ; then
    declare -x MSYS_NO_PATHCONV=1
    prefix+=(winpty)
    opts+=(--volume "/$(pwd -W)":/data)
else
    opts+=(--volume "${PWD}":/data)
fi

"${prefix[@]}" docker run "${opts[@]}" ${image} "${@}"

